root.id=root
root.password=root
admin.id=admin

james.host=127.0.0.1
james.control.port=9999
james.default_domain=example.com

# JMX Authentication (if enabled on James server)
jmx.username=james-admin
jmx.password=changeme

file.upload_folder=/WEB-INF/upload
file.download_folder=/WEB-INF/download
file.max_size=52428800